module.exports = {
  darkMode: 'media',
  content: [
    './src/**/*.html',
    './src/**/*.tsx',
    './src/**/*.ts',
    './src/**/*.jsx',
    './src/**/*.js',
  ],
  theme: {
    colors: {
      transparent: 'transparent',
      current: 'currentColor',
      'white': '#ffffff',
      'primary': '#5DD5FB',
      'on-primary': '#003543',
      'primary-container': '#004D61',
      'on-primary-container': '#B4EBFF',
      'secondary': '#B3CAD4',
      'on-secondary': '#1D333B',
      'secondary-container': '#354A52',
      'on-secondary-container': '#CFE6F0',
      'tertiary': '#C3C3EB',
      'on-tertiary': '#2C2E4D',
      'tertiary-container': '#424465',
      'on-tertiary-container': '#E0E0FF',
      'error': '#FFB4A9',
      'on-error': '#680003',
      'error-container': '#930006',
      'on-error-container': '#FFDAD4',
      'background': '#191C1D',
      'on-background': '#E1E2E4',
      'surface': '#191C1D',
      'on-surface': '#E1E2E4',
      'surface-variant': '#40484C',
      'on-surface-variant': '#40484C',
      'outline': '#8A9296'
    },
    extend: {}
  },
  plugins: [],
}